# Generated by Django 5.1.4 on 2025-01-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytransaction',
            name='is_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dailytransaction',
            name='is_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
