# Generated by Django 5.1.4 on 2025-01-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_details', '0002_alter_dailytransaction_is_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytransaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailytransaction',
            name='is_credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailytransaction',
            name='is_debit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
